### ISSUE TITLE
co-simulation jtag_vpi with openocd

### ISSUE THREAD

**Issue by curliph** [fjullien/jtag_vpi#3]
Hi,

I got problem when i do simulation my riscv jtag_dtm with jtag_vpi and openocd,
The problem is that when dtm report busy (op), openocd drive jtag to wrong tap states.
but if i just report ready(op= 00), there is no any problem.
I have work on the problem for days, but just on the side of dtm itself... seems that is not the point.
I know it should be not the problem of jtag_vpi, but do you have experiences about this work? 
Please help to give me some comment...

Thanks.

**Comment by fjullien** [comment]
Hi, I really don't know how riscv jtag_dtm works (and generally speaking riscv debug ecosystem).
I only used jtag_vpi with openrisc cpu.

Sorry for not helping you.

**Comment by curliph** [comment]
> Hi, I really don't know how riscv jtag_dtm works (and generally speaking riscv debug ecosystem).
> I only used jtag_vpi with openrisc cpu.
> 
> Sorry for not helping you.

Thanks for your reply.  I will try to report the problem to riscv-openocd group.
Anywhere, thanks for your great work.
