### ISSUE TITLE
Missing license for jtag_common.{c,h}

### ISSUE THREAD

**Issue by olofk** [fjullien/jtag_vpi#8]
I want to reuse pretty much all of jtag_common.{c,h} in another project, but I couldn't find a license for the files. Couldn't find a license for the other files either, but it's mainly the two mentioned files I'm interested in right now. As for my own contributions I'm happy to have them under whatever open source license you choose

**Comment by fjullien** [comment]
I'm sorry but yes, it's a mess. For now, I'll add you and @JanMatCodasip as authors in jtag_common files.
I'll put the same header as here: https://github.com/fjullien/jtag_vpi/blob/master/jtagServer.cpp#L1-L24

LAter, I think I'll move every files to SPDX style header (BSD).

**Comment by JanMatCodasip** [comment]
Hi @olofk, @fjullien,
Thank you for filling in the license. I am fine with releasing my contributions to jtag_vpi under any open-source license.

**Comment by fjullien** [comment]
Should be ok with this: fdabdab52
@olofk, Tell me if it's good for you.

**Comment by olofk** [comment]
That looks perfectly fine to me

And for the record, I have plenty of my own repos with the same situation that only get fixed when someone is complaining :)

**Comment by fjullien** [comment]
Ok fine, let's close it.
